<a href="https://colab.research.google.com/github/valid999/NLP-TensorFlow_Projects/blob/main/Language__model_implemednt__Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
### Libraries Used Tensorflow > 2.0 and keras
!pip install tensorflow-gpu


  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [3]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [4]:
## Tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### Sentences

sent = ['the glass of milk' ,
        'the glass of juice' ,
        'the cup of tea',
        'I am a good boy',
        'i am a good developer',
        'understand the meaning of words',
        'your videos are good'
        ]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size = 500

## One Hot Representation

In [14]:
onehot_repr = [one_hot(words , voc_size) for words in sent]
print(onehot_repr)

[[20, 39, 331, 393], [20, 39, 331, 232], [20, 142, 331, 442], [432, 134, 130, 296, 10], [432, 134, 130, 296, 481], [454, 20, 234, 331, 308], [202, 363, 116, 296]]


## Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [16]:
## Pre padding
sent_length = 8
embedded_docs = pad_sequences(onehot_repr , padding = 'pre' , maxlen = sent_length)
print(embedded_docs)

[[  0   0   0   0  20  39 331 393]
 [  0   0   0   0  20  39 331 232]
 [  0   0   0   0  20 142 331 442]
 [  0   0   0 432 134 130 296  10]
 [  0   0   0 432 134 130 296 481]
 [  0   0   0 454  20 234 331 308]
 [  0   0   0   0 202 363 116 296]]


In [17]:
## 10 feature dimensions
dim = 10

In [18]:
model = Sequential()
model.add(Embedding(voc_size , 10 , input_length = sent_length))
model.compile('adam' , 'mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
# The glass of milk
embedded_docs[0]

array([  0,   0,   0,   0,  20,  39, 331, 393], dtype=int32)

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 92ms/step


array([[-0.01589286, -0.02742937,  0.02218122,  0.02623929,  0.02291832,
        -0.01258658,  0.02542507,  0.03733437, -0.0373497 ,  0.04536009],
       [-0.01589286, -0.02742937,  0.02218122,  0.02623929,  0.02291832,
        -0.01258658,  0.02542507,  0.03733437, -0.0373497 ,  0.04536009],
       [-0.01589286, -0.02742937,  0.02218122,  0.02623929,  0.02291832,
        -0.01258658,  0.02542507,  0.03733437, -0.0373497 ,  0.04536009],
       [-0.01589286, -0.02742937,  0.02218122,  0.02623929,  0.02291832,
        -0.01258658,  0.02542507,  0.03733437, -0.0373497 ,  0.04536009],
       [-0.03794704,  0.01999393,  0.04419984, -0.03946738,  0.04127594,
         0.0311825 , -0.00683515,  0.03725933,  0.04283459,  0.01024514],
       [-0.01582485,  0.01586736,  0.03256248, -0.04603052,  0.01451811,
         0.017889  ,  0.02000965,  0.04992077,  0.0409114 ,  0.01353646],
       [ 0.02730007,  0.02362004, -0.01410924,  0.02722796, -0.02367629,
        -0.02671101, -0.03708826, -0.03733739

In [23]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 49ms/step
[[[-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832
   -0.01258658  0.02542507  0.03733437 -0.0373497   0.04536009]
  [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832
   -0.01258658  0.02542507  0.03733437 -0.0373497   0.04536009]
  [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832
   -0.01258658  0.02542507  0.03733437 -0.0373497   0.04536009]
  [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832
   -0.01258658  0.02542507  0.03733437 -0.0373497   0.04536009]
  [-0.03794704  0.01999393  0.04419984 -0.03946738  0.04127594
    0.0311825  -0.00683515  0.03725933  0.04283459  0.01024514]
  [-0.01582485  0.01586736  0.03256248 -0.04603052  0.01451811
    0.017889    0.02000965  0.04992077  0.0409114   0.01353646]
  [ 0.02730007  0.02362004 -0.01410924  0.02722796 -0.02367629
   -0.02671101 -0.03708826 -0.03733739  0.04740505 -0.0260379 ]
  [ 0.04587575  0.0308771   0.0164214  -0.0149316  -0.00841

In [24]:
embedded_docs[0]

array([  0,   0,   0,   0,  20,  39, 331, 393], dtype=int32)

In [25]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.03794704  0.01999393  0.04419984 -0.03946738  0.04127594  0.0311825
  -0.00683515  0.03725933  0.04283459  0.01024514]
 [-0.01582485  0.01586736  0.03256248 -0.04603052  0.01451811  0.017889
   0.02000965  0.04992077  0.0409114   0.01353646]
 [ 0.02730007  0.02362004 -0.01410924  0.02722796 -0.02367629 -0.02671101
  -0.03708826 -0.03733739  0.04740505 -0.0260379 ]
 [ 0.04587575  0.0308771   0.0164214  -0.0149316  -0.00841385 -0.00427538
  

In [26]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.03794704  0.01999393  0.04419984 -0.03946738  0.04127594  0.0311825
  -0.00683515  0.03725933  0.04283459  0.01024514]
 [-0.01582485  0.01586736  0.03256248 -0.04603052  0.01451811  0.017889
   0.02000965  0.04992077  0.0409114   0.01353646]
 [ 0.02730007  0.02362004 -0.01410924  0.02722796 -0.02367629 -0.02671101
  -0.03708826 -0.03733739  0.04740505 -0.0260379 ]
 [ 0.04587575  0.0308771   0.0164214  -0.0149316  -0.00841385 -0.00427538
  

# Assignment for the

In [28]:
### Assignment

task=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

## One hot

In [29]:
onehot_repr = [one_hot(words , voc_size) for words in task]
print(onehot_repr)

[[20, 179, 288, 130, 231, 485], [388, 15, 288, 90, 456, 256], [432, 104, 80, 428], [20, 295, 288, 6, 20, 37], [443, 79, 77, 288, 90, 456, 256], [430, 288, 90, 456, 16, 201]]


In [33]:
## Pre padding
sent_length = 8
embedded_docs_task = pad_sequences(onehot_repr , padding = 'post' , maxlen = sent_length)
print(embedded_docs_task)

[[ 20 179 288 130 231 485   0   0]
 [388  15 288  90 456 256   0   0]
 [432 104  80 428   0   0   0   0]
 [ 20 295 288   6  20  37   0   0]
 [443  79  77 288  90 456 256   0]
 [430 288  90 456  16 201   0   0]]


In [34]:
print(model.predict(embedded_docs_task[0]))

1/1 [==============================] - 0s 18ms/step
[[-0.03794704  0.01999393  0.04419984 -0.03946738  0.04127594  0.0311825
  -0.00683515  0.03725933  0.04283459  0.01024514]
 [ 0.04691513  0.03599203 -0.01449164 -0.04928589 -0.02641084  0.0440059
  -0.03178389  0.03351523  0.02897276 -0.02511761]
 [ 0.02991792  0.01596861  0.01886922  0.03939315 -0.00708335 -0.01401179
   0.02995812 -0.04264634 -0.0011536   0.01760424]
 [-0.00624908 -0.03687242 -0.02192396  0.04553698  0.00575771  0.01741678
  -0.02333404  0.02188969  0.03055686 -0.04775123]
 [ 0.04984225  0.0332675  -0.03533296  0.04959798 -0.03447503 -0.00732932
   0.00358033  0.03471655  0.02600602  0.00434582]
 [ 0.01757472  0.04102984 -0.02626623  0.04863584  0.02837977  0.03924957
   0.0188706   0.02920728 -0.036645    0.02019585]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
   0.02542507  0.03733437 -0.0373497   0.04536009]
 [-0.01589286 -0.02742937  0.02218122  0.02623929  0.02291832 -0.01258658
 